import type { Metadata } from "next";
import "./globals.css";
import { Mobilenav } from "./component/Mobilenav";
import TopHeader from "./component/top-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col font-sans antialiased bg-gray-50 text-gray-900">
        {/* top header  */}
        <TopHeader />
<Mobilenav />
        <header className="bg-gradient-to-r from-blue-600 to-blue-800 text-white p-4 shadow-md">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-2xl font-bold">My Awesome App</h1>
           
            <nav className="hidden md:flex items-center space-x-8"> {/* Changed to flex to align search/cart */}
              <ul className="flex space-x-6">
                <li>
                  <a href="/laptops" className="hover:text-blue-200 transition-colors font-semibold">
                    Laptops
                  </a>
                </li>
                <li>
                  <a href="/desktops" className="hover:text-blue-200 transition-colors font-semibold">
                    Desktops
                  </a>
                </li>
                <li>
                  <a href="/components" className="hover:text-blue-200 transition-colors font-semibold">
                    Components
                  </a>
                </li>
                <li>
                  <a href="/accessories" className="hover:text-blue-200 transition-colors font-semibold">
                    Accessories
                  </a>
                </li>
                <li>
                  <a href="/sale" className="hover:text-blue-200 transition-colors font-semibold text-red-300">
                    Sale!
                  </a>
                </li>
              </ul>

              {/* Search Bar */}
              <div className="relative">
                <input
                  type="text"
                  placeholder="Search products..."
                  className="p-2 pl-10 rounded-md text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-300 w-48"
                />
                <svg className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
              </div>

              {/* Shopping Cart Icon */}
              <a href="/cart" className="relative hover:text-blue-200 transition-colors">
                <svg className="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
                </svg>
                <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs font-bold rounded-full h-4 w-4 flex items-center justify-center">
                  3 {/* Example cart item count */}
                </span>
              </a>
            </nav>

          </div>
        </header>

        {/* main content   */}
        <main>
          {children}
        </main>
        {/* footer content */}
        <footer className="bg-gray-800 text-white p-4 mt-auto shadow-inner">
          <div className="container mx-auto text-center">
            <p>&copy; {new Date().getFullYear()} My Awesome App. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
