
import type { Metadata } from "next";
import "./globals.css";
import { Mobilenav } from "./component/Mobilenav";
import TopHeader from "./component/top-header";
import { Header } from "./component/header";
import FooterTop from "./component/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col font-sans antialiased  text-gray-900">
        {/* top header  */}
        <TopHeader />
        <Mobilenav />
        <Header />


        {/* main content   */}
        <main className="flex-grow bg-gray-700 text-white">
          {children}
        </main>
        {/* footer content */}
        <footer className="bg-gray-800 text-white">
          <div className="container mx-auto px-4 py-8">
            <FooterTop />
          </div>
        </footer>
      </body>
    </html>
  );
}
